version: "3.9" # optional since v1.27.0
services:
  rc50next:
    build: ./rc50next
    ports:
      - "3000:3000"
    networks:
      - rc50app
  rc50ws:
    ports: 
      - "3002:3002"
    build: ./rc50ws
    privileged: true
    networks:
      - rc50app
  rc50db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
       - "27017:27017"
    volumes:
       - ./rc50db:/data/db
    networks:
      - rc50app
  rc50acq:
    ports:
      - "3001:3001"
      - 192.168.1.5:502:502
      - 192.168.1.5:8088:8088
    build: ./rc50acq
    privileged: true
    networks:
      - rc50app
    depends_on:
      - rc50ws

networks:
  rc50app:
    driver: bridge
